name: "text_encoder"
backend: "python"
max_batch_size: 1

input [
  {
    name: "image1_path"
    data_type: TYPE_STRING
    dims: [ -1 ]
  },
  {
    name: "image2_path"
    data_type: TYPE_STRING
    dims: [ -1 ]
  },
  {
    name: "prompt"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

output [
  {
    name: "positive_encoding"
    data_type: TYPE_FP32
    dims: [ 437, 3584 ]
  },
  {
    name: "negative_encoding"
    data_type: TYPE_FP32
    dims: [ 407, 3584 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
