name: "sampling"
backend: "python"
max_batch_size: 1

input [
  {
    name: "positive_encoding"
    data_type: TYPE_FP32
    dims: [ 437, 3584 ]
  },  {
    name: "negative_encoding"
    data_type: TYPE_FP32
    dims: [ 407, 3584 ]
  },  {
    name: "latent_image"
    data_type: TYPE_FP32
    dims: [ 16, 1, 147, 110 ]
  },  {
    name: "seed"
    data_type: TYPE_INT64
    dims: [ ]
  }
]

output {
  name: "sampled_latent"
  data_type: TYPE_FP32
  dims: [ 16, 1, 147, 110 ]
}

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
